### ISSUE TITLE
Problems with new installation

### ISSUE THREAD

**Issue by Develbold** [ChildMindInstitute/mindlogger-backend#993]
I'm trying to do a clean install. Running command 

`girderformindlogger build`

from step3 produces the following error message:

>/.../mindlogger-backend/girderformindlogger/__init__.py:42: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if env is not 'localhost':
Traceback (most recent call last):
  File "/.../backend/lib/python3.8/site-packages/cherrypy/lib/reprconf.py", line 213, in as_dict
    value = unrepr(value)
  File "/.../backend/lib/python3.8/site-packages/cherrypy/lib/reprconf.py", line 508, in unrepr
    return b.build(obj)
  File "/.../backend/lib/python3.8/site-packages/cherrypy/lib/reprconf.py", line 354, in build
    raise TypeError('unrepr does not recognize %s' %
TypeError: unrepr does not recognize 'Constant'

> During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/.../backend/bin/girderformindlogger", line 33, in <module>
    sys.exit(load_entry_point('girderformindlogger', 'console_scripts', 'girderformindlogger')())
  File "/.../backend/bin/girderformindlogger", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/.../mindlogger-backend/girderformindlogger/__init__.py", line 34, in <module>
    config.loadConfig()  # Populate the config info at import time
  File "/.../mindlogger-backend/girderformindlogger/utility/config.py", line 54, in loadConfig
    _loadConfigsByPrecedent()
  File "/.../mindlogger-backend/girderformindlogger/utility/config.py", line 49, in _loadConfigsByPrecedent
    _mergeConfig(curConfigPath)
  File "/.../mindlogger-backend/girderformindlogger/utility/config.py", line 15, in _mergeConfig
    cherrypy._cpconfig.merge(cherrypy.config, filename)
  File "/.../backend/lib/python3.8/site-packages/cherrypy/_cpconfig.py", line 139, in merge
    for section, value_map in reprconf.as_dict(other).items():
  File "/.../backend/lib/python3.8/site-packages/cherrypy/lib/reprconf.py", line 46, in as_dict
    config = Parser().dict_from_file(config)
  File "/.../backend/lib/python3.8/site-packages/cherrypy/lib/reprconf.py", line 228, in dict_from_file
    return self.as_dict()
  File "/.../backend/lib/python3.8/site-packages/cherrypy/lib/reprconf.py", line 219, in as_dict
    raise ValueError(msg, x.__class__.__name__, x.args)
ValueError: ('Config error in section: \'global\', option: \'server.socket_host\', value: \'"127.0.0.1"\'. Config values must be valid Python.', 'TypeError', ("unrepr does not recognize 'Constant'",))

what am I missing here?

**Comment by TheMightyMoe** [comment]
Sadly getting the same error message

**Comment by jj105** [comment]
could you try using python3.7?
I remind that I got similar issue in the past when I was using python3.8.

**Comment by devmrac** [comment]
python 3.7 failed for me too after having had the same issues with 3.8

**Comment by jj105** [comment]
@devmrac could you show me your error message?

**Comment by TheMightyMoe** [comment]
@jj105 that the error. After running the setupscript and installing pandas somentimes it comes also tho a numpy error: NUMPY_IMPORT_ARRAY_RETVAL
Log (reduced to the most nessecary):
`Running setup.py install for pandas ... error
    ERROR: Command errored out with exit status 1:
     command: /home/ubuntu/girder_env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-07_0_j_n/pandas_32df6ba889094767a835d17f2ebcf3c6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-07_0_j_n/pandas_32df6ba889094767a835d17f2ebcf3c6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6ktae7yf/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntu/girder_env/include/site/python3.8/pandas
         cwd: /tmp/pip-install-07_0_j_n/pandas_32df6ba889094767a835d17f2ebcf3c6/
    Complete output (1731 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/pandas
[...]
In file included from pandas/_libs/tslibs/src/datetime/np_datetime.c:24:
    /usr/include/python3.8/datetime.h:189:25: warning: ‘PyDateTimeAPI’ defined but not used [-Wunused-variable]
      189 | static PyDateTime_CAPI *PyDateTimeAPI = NULL;
          |                         ^~~~~~~~~~~~~
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNPY_NO_DEPRECATED_API=0 -Ipandas/_libs/src/klib -Ipandas/_libs/src -Ipandas/_libs/tslibs/src -Ipandas/_libs/tslibs -I/home/ubuntu/girder_env/lib/python3.8/site-packages/numpy/core/include -I/home/ubuntu/girder_env/include -I/usr/include/python3.8 -c pandas/_libs/tslibs/src/datetime/np_datetime_strings.c -o build/temp.linux-x86_64-3.8/pandas/_libs/tslibs/src/datetime/np_datetime_strings.o -Wno-unused-function
    In file included from pandas/_libs/tslibs/src/datetime/np_datetime.h:25,
                     from pandas/_libs/tslibs/src/datetime/np_datetime_strings.c:37:
    /usr/include/python3.8/datetime.h:189:25: warning: ‘PyDateTimeAPI’ defined but not used [-Wunused-variable]
      189 | static PyDateTime_CAPI *PyDateTimeAPI = NULL;
          |                         ^~~~~~~~~~~~~
[...]

    pandas/_libs/internals.c: In function ‘__pyx_gb_6pandas_5_libs_9internals_8generator’:
    pandas/_libs/internals.c:9237:36: warning: ‘__pyx_t_23’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     9237 |         __pyx_cur_scope->__pyx_t_9 = __pyx_t_23;
          |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
    pandas/_libs/internals.c:8964:36: warning: ‘__pyx_t_11’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     8964 |         __pyx_cur_scope->__pyx_t_5 = __pyx_t_11;
          |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
    pandas/_libs/internals.c:8961:36: warning: ‘__pyx_t_6’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     8961 |         __pyx_cur_scope->__pyx_t_4 = __pyx_t_6;
          |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
    pandas/_libs/internals.c:8966:36: warning: ‘__pyx_t_15’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     8966 |         __pyx_cur_scope->__pyx_t_8 = __pyx_t_15;
          |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
    pandas/_libs/internals.c:8965:36: warning: ‘__pyx_t_12’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     8965 |         __pyx_cur_scope->__pyx_t_7 = __pyx_t_12;
          |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
[...]

    pandas/_libs/src/ujson/python/objToJSON.c:181:12: error: ‘NUMPY_IMPORT_ARRAY_RETVAL’ undeclared (first use in this function)
      181 |     return NUMPY_IMPORT_ARRAY_RETVAL;
          |            ^~~~~~~~~~~~~~~~~~~~~~~~~
    pandas/_libs/src/ujson/python/objToJSON.c:181:12: note: each undeclared identifier is reported only once for each function it appears in
    pandas/_libs/src/ujson/python/objToJSON.c:182:1: warning: control reaches end of non-void function [-Wreturn-type]
      182 | }
          | ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`

**Comment by jj105** [comment]
@TheMightyMoe did you try using python3.7?

**Comment by TheMightyMoe** [comment]
@jj105 see above
Waiting for a new release, as i heard there will be some

**Comment by jj105** [comment]
@TheMightyMoe
I think your above message is one from python3.8 not python3.7.

**Comment by TheMightyMoe** [comment]
@jj105 
Oh It seems you are right (.../usr/include/python3.8/datetime.h:189:25: warning...) strange...
Because we uninstalled python 3.8 and installed python 3.8
We will check it. We are using Ubuntu Server

**Comment by WorldImpex** [comment]
TheMightyMoe or Develbold - Do you require any further assistance?

**Comment by TheMightyMoe** [comment]
The problem is, that 
`sudo apt-get install pip`
installes the newest Version of python (in my case 3.8) even if I remove python 3.8 with all its dependencies and install python 3.7. The command
`sudo apt-get install python3.7-pip`
unfortunately doesn't exist.

Does anyone have a solution or a hint to solve this?
Or is a new verion of mindlogger backend available?

**Comment by TheMightyMoe** [comment]
We tried it with installing a python3.7 version of pip using the script python3.7 get-pip.py installed using
`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`
So Pip was successfully installed without using python3.8 packaged but unfortunately this has not been the solution.
Here the full output:
`ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t4krda2_/psutil_0055b38908e445a59c0d66e01cd7045d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t4krda2_/psutil_0055b38908e445a59c0d66e01cd7045d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7n8g0cgs/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/psutil
         cwd: /tmp/pip-install-t4krda2_/psutil_0055b38908e445a59c0d66e01cd7045d/
    Complete output (44 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/psutil
    copying psutil/_psosx.py -> build/lib.linux-x86_64-3.7/psutil
    copying psutil/_compat.py -> build/lib.linux-x86_64-3.7/psutil
    copying psutil/_psposix.py -> build/lib.linux-x86_64-3.7/psutil
    copying psutil/__init__.py -> build/lib.linux-x86_64-3.7/psutil
    copying psutil/_common.py -> build/lib.linux-x86_64-3.7/psutil
    copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.7/psutil
    copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.7/psutil
    copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.7/psutil
    copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.7/psutil
    copying psutil/_psaix.py -> build/lib.linux-x86_64-3.7/psutil
    creating build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/runner.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.7/psutil/tests
    running build_ext
    building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/psutil
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.7-uNfk84/python3.7-3.7.10=. -fstack-protector-strong -Wformat -Werror=format-security -g -fdebug-prefix-map=/build/python3.7-uNfk84/python3.7-3.7.10=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=566 -DPSUTIL_LINUX=1 -I/usr/include/python3.7m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.7/psutil/_psutil_common.o
    psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
        9 | #include <Python.h>
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

Its a different error then the NUMPY Error from using python3.8

**Comment by WorldImpex** [comment]
@TheMightyMoe 

Without having access to your environment it is hard to help further with your request

**Comment by TheMightyMoe** [comment]
@WorldImpex 

Having you access to our mindlogger backend would not be possible, but we could organize a video call with screenshare.
Is this possible for you?

**Comment by WorldImpex** [comment]
Could you provide contact details @TheMightyMoe ?

**Comment by TheMightyMoe** [comment]
Thank you for your help @WorldImpex :) I have send you an pm
